<template>
  <div
    class="condition-industry-select"
    :class="{ open: visable, 'is-select': count }"
    @mouseenter="changeVisable(true)"
    @mouseleave="changeFatherVisable(false)"
  >
    <div class="current-select">
      <span class="placeholder-text">公司行业</span>
      <em class="select-num" v-if="count">({{ count }})</em>
    </div>
    <div
      class="filter-select-dropdown"
      @mouseenter="changeVisable(true, 'child')"
      @mouseleave="changeVisable(false)"
    >
      <ul>
        <li class="clearfix" v-for="item in list" :key="item.code">
          <span class="label">{{ item.name }}</span>
          <div class="select-list">
            <a
              @click="changeCheck(cItem)"
              v-for="cItem in item.subLevelModelList"
              :key="cItem.code"
              :class="{ active: ids.includes(cItem.code) }"
              >{{ cItem.name }} <el-icon v-show="ids.includes(cItem.code)"><Check /></el-icon></a>
          </div>
        </li>
      </ul>
    </div>
  </div>
</template>

<script setup>
import { ElMessage } from "element-plus";
import { ref, reactive, computed } from "vue";
const list = [
  {
    code: 100000,
    name: "互联网/IT/电子/通信",
    tip: null,
    subLevelModelList: [
      {
        code: 100001,
        name: "电子商务",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 100002,
        name: "游戏",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 100003,
        name: "媒体",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 100004,
        name: "广告营销",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 100005,
        name: "数据服务",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 100006,
        name: "医疗健康",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 100007,
        name: "生活服务",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 100008,
        name: "O2O",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 100009,
        name: "旅游",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 100010,
        name: "分类信息",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 100011,
        name: "音乐/视频/阅读",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 100012,
        name: "在线教育",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 100013,
        name: "社交网络",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 100014,
        name: "人力资源服务",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 100015,
        name: "企业服务",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 100016,
        name: "信息安全",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 100017,
        name: "新零售",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 100018,
        name: "智能硬件",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 100019,
        name: "移动互联网",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 100020,
        name: "互联网",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 100021,
        name: "计算机软件",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 100022,
        name: "计算机硬件",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 100023,
        name: "计算机服务",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 100024,
        name: "通信/网络设备",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 100025,
        name: "运营商/增值服务",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 100026,
        name: "电子/半导体/集成电路",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 100027,
        name: "消费电子",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
    ],
    firstChar: null,
    pinyin: null,
    rank: 0,
    mark: 0,
    positionType: 0,
    cityType: 0,
    capital: 0,
    color: null,
    recruitmentType: null,
    cityCode: null,
    regionCode: 0,
    value: null,
  },
  {
    code: 100100,
    name: "广告/传媒/文化/体育",
    tip: null,
    subLevelModelList: [
      {
        code: 100101,
        name: "广告/公关/会展",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 100102,
        name: "新闻/出版",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 100103,
        name: "广播/影视",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 100104,
        name: "文化/体育/娱乐",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
    ],
    firstChar: null,
    pinyin: null,
    rank: 0,
    mark: 0,
    positionType: 0,
    cityType: 0,
    capital: 0,
    color: null,
    recruitmentType: null,
    cityCode: null,
    regionCode: 0,
    value: null,
  },
  {
    code: 100200,
    name: "金融",
    tip: null,
    subLevelModelList: [
      {
        code: 100201,
        name: "银行",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 100202,
        name: "保险",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 100203,
        name: "证券/期货",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 100204,
        name: "基金",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 100205,
        name: "信托",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 100206,
        name: "互联网金融",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 100207,
        name: "投资/融资",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 100208,
        name: "租赁/拍卖/典当/担保",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
    ],
    firstChar: null,
    pinyin: null,
    rank: 0,
    mark: 0,
    positionType: 0,
    cityType: 0,
    capital: 0,
    color: null,
    recruitmentType: null,
    cityCode: null,
    regionCode: 0,
    value: null,
  },
  {
    code: 100300,
    name: "教育培训",
    tip: null,
    subLevelModelList: [
      {
        code: 100301,
        name: "学前教育",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 100302,
        name: "院校",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 100303,
        name: "培训机构",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 100304,
        name: "学术/科研",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
    ],
    firstChar: null,
    pinyin: null,
    rank: 0,
    mark: 0,
    positionType: 0,
    cityType: 0,
    capital: 0,
    color: null,
    recruitmentType: null,
    cityCode: null,
    regionCode: 0,
    value: null,
  },
  {
    code: 100400,
    name: "制药/医疗",
    tip: null,
    subLevelModelList: [
      {
        code: 100401,
        name: "制药",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 100402,
        name: "医疗/护理/卫生",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 100403,
        name: "医疗设备/器械",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
    ],
    firstChar: null,
    pinyin: null,
    rank: 0,
    mark: 0,
    positionType: 0,
    cityType: 0,
    capital: 0,
    color: null,
    recruitmentType: null,
    cityCode: null,
    regionCode: 0,
    value: null,
  },
  {
    code: 100500,
    name: "交通/物流/贸易/零售",
    tip: null,
    subLevelModelList: [
      {
        code: 100501,
        name: "交通/运输",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 100502,
        name: "物流/仓储",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 100503,
        name: "批发/零售",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 100504,
        name: "贸易/进出口",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
    ],
    firstChar: null,
    pinyin: null,
    rank: 0,
    mark: 0,
    positionType: 0,
    cityType: 0,
    capital: 0,
    color: null,
    recruitmentType: null,
    cityCode: null,
    regionCode: 0,
    value: null,
  },
  {
    code: 100600,
    name: "专业服务",
    tip: null,
    subLevelModelList: [
      {
        code: 100601,
        name: "咨询",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 100602,
        name: "法律",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 100603,
        name: "翻译",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 100604,
        name: "人力资源服务",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 100605,
        name: "财务/审计/税务",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 100606,
        name: "检测/认证",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 100607,
        name: "专利/商标/知识产权",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 100608,
        name: "其他专业服务",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
    ],
    firstChar: null,
    pinyin: null,
    rank: 0,
    mark: 0,
    positionType: 0,
    cityType: 0,
    capital: 0,
    color: null,
    recruitmentType: null,
    cityCode: null,
    regionCode: 0,
    value: null,
  },
  {
    code: 100700,
    name: "房地产/建筑",
    tip: null,
    subLevelModelList: [
      {
        code: 100701,
        name: "房地产开发",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 100702,
        name: "工程施工",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 100703,
        name: "建筑设计",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 100704,
        name: "装修装饰",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 100705,
        name: "建材",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 100706,
        name: "地产经纪/中介",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 100707,
        name: "物业服务",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
    ],
    firstChar: null,
    pinyin: null,
    rank: 0,
    mark: 0,
    positionType: 0,
    cityType: 0,
    capital: 0,
    color: null,
    recruitmentType: null,
    cityCode: null,
    regionCode: 0,
    value: null,
  },
  {
    code: 100800,
    name: "汽车",
    tip: null,
    subLevelModelList: [
      {
        code: 100801,
        name: "汽车生产",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 100802,
        name: "汽车零部件",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 100803,
        name: "4S店/后市场",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
    ],
    firstChar: null,
    pinyin: null,
    rank: 0,
    mark: 0,
    positionType: 0,
    cityType: 0,
    capital: 0,
    color: null,
    recruitmentType: null,
    cityCode: null,
    regionCode: 0,
    value: null,
  },
  {
    code: 100900,
    name: "机械/制造",
    tip: null,
    subLevelModelList: [
      {
        code: 100901,
        name: "机械设备/机电/重工",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 100902,
        name: "仪器仪表/工业自动化",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 100903,
        name: "原材料及加工/模具",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 100904,
        name: "印刷/包装/造纸",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 100905,
        name: "船舶/航空/航天",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
    ],
    firstChar: null,
    pinyin: null,
    rank: 0,
    mark: 0,
    positionType: 0,
    cityType: 0,
    capital: 0,
    color: null,
    recruitmentType: null,
    cityCode: null,
    regionCode: 0,
    value: null,
  },
  {
    code: 101000,
    name: "消费品",
    tip: null,
    subLevelModelList: [
      {
        code: 101001,
        name: "食品/饮料/烟酒",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 101002,
        name: "日化",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 101003,
        name: "服装/纺织/皮革",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 101004,
        name: "家具/家电/家居",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 101005,
        name: "玩具/礼品",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 101006,
        name: "珠宝/首饰",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 101007,
        name: "工艺品/收藏品",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 101008,
        name: "办公用品及设备",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
    ],
    firstChar: null,
    pinyin: null,
    rank: 0,
    mark: 0,
    positionType: 0,
    cityType: 0,
    capital: 0,
    color: null,
    recruitmentType: null,
    cityCode: null,
    regionCode: 0,
    value: null,
  },
  {
    code: 101100,
    name: "服务业",
    tip: null,
    subLevelModelList: [
      {
        code: 101101,
        name: "餐饮",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 101102,
        name: "酒店",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 101103,
        name: "旅游",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 101104,
        name: "美容/美发",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 101105,
        name: "婚庆/摄影",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 101106,
        name: "其他服务业",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 101107,
        name: "休闲/娱乐",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 101108,
        name: "回收/维修",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 101109,
        name: "家政服务",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 101110,
        name: "宠物服务",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
    ],
    firstChar: null,
    pinyin: null,
    rank: 0,
    mark: 0,
    positionType: 0,
    cityType: 0,
    capital: 0,
    color: null,
    recruitmentType: null,
    cityCode: null,
    regionCode: 0,
    value: null,
  },
  {
    code: 101200,
    name: "能源/化工/环保",
    tip: null,
    subLevelModelList: [
      {
        code: 101201,
        name: "石油/石化",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 101202,
        name: "化工",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 101203,
        name: "矿产/地质",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 101204,
        name: "采掘/冶炼",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 101205,
        name: "电力/热力/燃气/水利",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 101206,
        name: "新能源",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 101207,
        name: "环保",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
    ],
    firstChar: null,
    pinyin: null,
    rank: 0,
    mark: 0,
    positionType: 0,
    cityType: 0,
    capital: 0,
    color: null,
    recruitmentType: null,
    cityCode: null,
    regionCode: 0,
    value: null,
  },
  {
    code: 101300,
    name: "政府/非盈利机构/其他",
    tip: null,
    subLevelModelList: [
      {
        code: 101301,
        name: "政府/公共事业",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 101302,
        name: "非盈利机构",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 101303,
        name: "农/林/牧/渔",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
      {
        code: 101304,
        name: "其他行业",
        tip: null,
        subLevelModelList: null,
        firstChar: null,
        pinyin: null,
        rank: 0,
        mark: 0,
        positionType: 0,
        cityType: 0,
        capital: 0,
        color: null,
        recruitmentType: null,
        cityCode: null,
        regionCode: 0,
        value: null,
      },
    ],
    firstChar: null,
    pinyin: null,
    rank: 0,
    mark: 0,
    positionType: 0,
    cityType: 0,
    capital: 0,
    color: null,
    recruitmentType: null,
    cityCode: null,
    regionCode: 0,
    value: null,
  },
];
const allData = ref(
  list
    .map((item) => item.subLevelModelList.map((cItem) => ({ ...cItem })))
    .flat()
);
const ids = ref([]);
const count=computed(()=> ids.value.length);
const visable = ref(false);
const isChild = ref(false);
const changeVisable = (val, child) => {
  visable.value = val;
  isChild.value = child && val;
};
const changeFatherVisable = () => {
  setTimeout(() => {
    if (!isChild.value) {
      visable.value = false;
    }
  }, 50);
};

const changeCheck = (item) => {
  if (ids.value.includes(item.code)) {
    ids.value.splice(ids.value.indexOf(item.code), 1);
  } else {
    if(ids.value.length===3){
      ElMessage.error('最多选择3个哦')
      return false
    }
    ids.value.push(item.code);
  }
};
</script>

<style lang="scss" scoped>
.condition-industry-select {
  float: left;
  margin-top: 20px;
  margin-right: 20px;
  position: relative;
  background: #f8f8f8;
  border-radius: 4px;
  overflow: hidden;
  .current-select {
    position: relative;
    display: inline-block;
    font-size: 14px;
    font-weight: 400;
    color: #222;
    line-height: 20px;
    padding: 6px 24px 6px 12px;
    cursor: pointer;
    transition: all 0.2s linear;
    .placeholder-text {
      display: inline-block;
      max-width: 100px;
      overflow: hidden;
      text-overflow: ellipsis;
      white-space: nowrap;
      vertical-align: bottom;
    }
    .select-num{
    font-style: normal;
    display: inline-block;
    margin-left: 2px;
    vertical-align: bottom;
}
  }
  .current-select:after {
    content: " ";
    position: absolute;
    top: 12px;
    right: 12px;
    width: 4px;
    height: 7px;
    background: url(@/assets/arrow.png) -6px -16px/10px auto no-repeat;
    transform: rotate(90deg);
    z-index: 1;
  }
  .filter-select-dropdown {
    position: absolute;
    top: 40px;
    left: 0;
    z-index: 4;
    padding: 4px 0;
    background: #fff;
    overflow: auto;
    overflow: overlay;
    border-radius: 12px;
    border: 1px solid #ebeef5;
    transition: opacity 0.2s linear;
    ul {
      width: 884px;
      height: 286px;
      li {
        position: relative;
        padding-left: 182px;
        .label {
          position: absolute;
          top: 8px;
          left: 0;
          z-index: 1;
          width: 182px;
          padding: 0 16px;
          font-size: 14px;
          font-weight: 500;
          color: #222;
          line-height: 20px;
          white-space: nowrap;
          overflow: hidden;
          text-overflow: ellipsis;
        }
        .select-list {
          width: 100%;
          overflow: hidden;
          a {
            position: relative;
            width: 25%;
            float: left;
            padding: 8px 24px 8px 8px;
            font-size: 14px;
            font-weight: 400;
            color: #333;
            line-height: 20px;
            border-radius: 4px;
            white-space: nowrap;
            overflow: hidden;
            text-overflow: ellipsis;
            transition: all 0.2s linear;
            .el-icon {
              position: absolute;
              font-weight: 700;
              font-size: 12px;
              top: 12px;
              right: 8px;
              z-index: 1;
              color: #00a6a7;
            }
          }
          a.active {
            color: #00a6a7;
            font-weight: 500;
          }
        }
        a:hover {
          background: #f8f8f8;
          color: #00a6a7;
          font-weight: 500;
        }
      }
    }
  }
}

.condition-industry-select.open {
  background: #e5f8f8;
  overflow: visible;
}
.condition-industry-select.open .current-select:after {
  background-position: -6px -8px;
  transform: rotate(270deg);
}
.condition-industry-select.is-select .current-select:after {
  background: url(@/assets/arrow.png) -6px -8px/10px auto no-repeat;
}
.condition-industry-select.is-select .current-select {
  color: #00a6a7;
  background: #e5f8f8;
  font-weight: 500;
}
.condition-industry-select.open .current-select {
  color: #00a6a7;
}
.condition-industry-select.open:after {
  content: " ";
}
.condition-industry-select:after {
  content: none;
  position: absolute;
  left: 0;
  right: 0;
  bottom: -8px;
  height: 8px;
  z-index: 4;
  background: transparent;
}
</style>